// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="kernel5,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160t-fbg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.717000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=2,HLS_SYN_FF=464,HLS_SYN_LUT=481,HLS_VERSION=2019_2}" *)

module kernel5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bound,
        a_address0,
        a_ce0,
        a_q0,
        b_address0,
        b_ce0,
        b_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] bound;
output  [9:0] a_address0;
output   a_ce0;
input  [31:0] a_q0;
output  [9:0] b_address0;
output   b_ce0;
input  [31:0] b_q0;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg a_ce0;
reg b_ce0;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] or_ln6_1_fu_121_p2;
reg   [0:0] or_ln6_1_reg_211;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln6_4_fu_143_p2;
reg   [0:0] icmp_ln6_4_reg_226;
wire   [31:0] i_fu_149_p2;
reg   [31:0] i_reg_231;
reg   [31:0] a_load_reg_236;
wire    ap_CS_fsm_state3;
reg   [31:0] b_load_reg_241;
wire   [31:0] grp_fu_83_p2;
reg   [31:0] tmp_reg_246;
wire    ap_CS_fsm_state7;
reg  signed [31:0] i_0_reg_72;
wire    ap_CS_fsm_state9;
wire   [0:0] and_ln6_fu_201_p2;
wire  signed [63:0] sext_ln6_fu_127_p1;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state8;
wire   [31:0] bitcast_ln6_1_fu_91_p1;
wire   [7:0] tmp_2_fu_95_p4;
wire   [22:0] trunc_ln6_fu_105_p1;
wire   [0:0] icmp_ln6_3_fu_115_p2;
wire   [0:0] icmp_ln6_fu_109_p2;
wire   [21:0] tmp_4_fu_133_p4;
wire   [31:0] bitcast_ln6_fu_155_p1;
wire   [7:0] tmp_1_fu_158_p4;
wire   [22:0] trunc_ln6_1_fu_168_p1;
wire   [0:0] icmp_ln6_2_fu_178_p2;
wire   [0:0] icmp_ln6_1_fu_172_p2;
wire   [0:0] or_ln6_fu_184_p2;
wire   [0:0] and_ln6_1_fu_190_p2;
wire   [0:0] grp_fu_87_p2;
wire   [0:0] and_ln6_2_fu_195_p2;
reg   [8:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
end

kernel5_fadd_32nsbkb #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
kernel5_fadd_32nsbkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_load_reg_236),
    .din1(b_load_reg_241),
    .ce(1'b1),
    .dout(grp_fu_83_p2)
);

kernel5_fcmp_32nscud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
kernel5_fcmp_32nscud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_246),
    .din1(bound),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_87_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln6_fu_201_p2) & (1'b1 == ap_CS_fsm_state9))) begin
        i_0_reg_72 <= i_reg_231;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_72 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        a_load_reg_236 <= a_q0;
        b_load_reg_241 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_231 <= i_fu_149_p2;
        icmp_ln6_4_reg_226 <= icmp_ln6_4_fu_143_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        or_ln6_1_reg_211 <= or_ln6_1_fu_121_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_reg_246 <= grp_fu_83_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln6_fu_201_p2) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln6_fu_201_p2) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        b_ce0 = 1'b1;
    end else begin
        b_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'd0 == and_ln6_fu_201_p2) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = sext_ln6_fu_127_p1;

assign and_ln6_1_fu_190_p2 = (or_ln6_fu_184_p2 & or_ln6_1_reg_211);

assign and_ln6_2_fu_195_p2 = (grp_fu_87_p2 & and_ln6_1_fu_190_p2);

assign and_ln6_fu_201_p2 = (icmp_ln6_4_reg_226 & and_ln6_2_fu_195_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = tmp_reg_246;

assign b_address0 = sext_ln6_fu_127_p1;

assign bitcast_ln6_1_fu_91_p1 = bound;

assign bitcast_ln6_fu_155_p1 = tmp_reg_246;

assign i_fu_149_p2 = ($signed(32'd1) + $signed(i_0_reg_72));

assign icmp_ln6_1_fu_172_p2 = ((tmp_1_fu_158_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln6_2_fu_178_p2 = ((trunc_ln6_1_fu_168_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln6_3_fu_115_p2 = ((trunc_ln6_fu_105_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln6_4_fu_143_p2 = (($signed(tmp_4_fu_133_p4) < $signed(22'd1)) ? 1'b1 : 1'b0);

assign icmp_ln6_fu_109_p2 = ((tmp_2_fu_95_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln6_1_fu_121_p2 = (icmp_ln6_fu_109_p2 | icmp_ln6_3_fu_115_p2);

assign or_ln6_fu_184_p2 = (icmp_ln6_2_fu_178_p2 | icmp_ln6_1_fu_172_p2);

assign sext_ln6_fu_127_p1 = i_0_reg_72;

assign tmp_1_fu_158_p4 = {{bitcast_ln6_fu_155_p1[30:23]}};

assign tmp_2_fu_95_p4 = {{bitcast_ln6_1_fu_91_p1[30:23]}};

assign tmp_4_fu_133_p4 = {{i_0_reg_72[31:10]}};

assign trunc_ln6_1_fu_168_p1 = bitcast_ln6_fu_155_p1[22:0];

assign trunc_ln6_fu_105_p1 = bitcast_ln6_1_fu_91_p1[22:0];

endmodule //kernel5
