// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "kernel3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic kernel3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic kernel3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> kernel3::ap_ST_fsm_state1 = "1";
const sc_lv<9> kernel3::ap_ST_fsm_state2 = "10";
const sc_lv<9> kernel3::ap_ST_fsm_state3 = "100";
const sc_lv<9> kernel3::ap_ST_fsm_state4 = "1000";
const sc_lv<9> kernel3::ap_ST_fsm_state5 = "10000";
const sc_lv<9> kernel3::ap_ST_fsm_state6 = "100000";
const sc_lv<9> kernel3::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> kernel3::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> kernel3::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> kernel3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> kernel3::ap_const_lv32_1 = "1";
const sc_lv<32> kernel3::ap_const_lv32_2 = "10";
const sc_lv<32> kernel3::ap_const_lv32_3 = "11";
const sc_lv<32> kernel3::ap_const_lv32_7 = "111";
const sc_lv<11> kernel3::ap_const_lv11_0 = "00000000000";
const sc_lv<32> kernel3::ap_const_lv32_8 = "1000";
const sc_lv<32> kernel3::ap_const_lv32_4 = "100";
const sc_lv<11> kernel3::ap_const_lv11_400 = "10000000000";
const sc_lv<11> kernel3::ap_const_lv11_1 = "1";
const sc_lv<1> kernel3::ap_const_lv1_1 = "1";
const bool kernel3::ap_const_boolean_1 = true;

kernel3::kernel3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    kernel3_fadd_32nsbkb_U1 = new kernel3_fadd_32nsbkb<1,4,32,32,32>("kernel3_fadd_32nsbkb_U1");
    kernel3_fadd_32nsbkb_U1->clk(ap_clk);
    kernel3_fadd_32nsbkb_U1->reset(ap_rst);
    kernel3_fadd_32nsbkb_U1->din0(hist_load_reg_133);
    kernel3_fadd_32nsbkb_U1->din1(weight_load_reg_128);
    kernel3_fadd_32nsbkb_U1->ce(ap_var_for_const0);
    kernel3_fadd_32nsbkb_U1->dout(grp_fu_78_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln5_fu_82_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln5_fu_82_p2 );

    SC_METHOD(thread_hist_address0);
    sensitive << ( hist_addr_reg_123 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( sext_ln6_fu_100_p1 );

    SC_METHOD(thread_hist_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_hist_d0);
    sensitive << ( tmp_reg_138 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_hist_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_i_fu_88_p2);
    sensitive << ( i_0_reg_67 );

    SC_METHOD(thread_icmp_ln5_fu_82_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_67 );

    SC_METHOD(thread_index_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln6_fu_94_p1 );

    SC_METHOD(thread_index_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sext_ln6_fu_100_p1);
    sensitive << ( index_q0 );

    SC_METHOD(thread_weight_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln6_fu_94_p1 );

    SC_METHOD(thread_weight_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_zext_ln6_fu_94_p1);
    sensitive << ( i_0_reg_67 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln5_fu_82_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "kernel3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, hist_address0, "(port)hist_address0");
    sc_trace(mVcdFile, hist_ce0, "(port)hist_ce0");
    sc_trace(mVcdFile, hist_we0, "(port)hist_we0");
    sc_trace(mVcdFile, hist_d0, "(port)hist_d0");
    sc_trace(mVcdFile, hist_q0, "(port)hist_q0");
    sc_trace(mVcdFile, weight_address0, "(port)weight_address0");
    sc_trace(mVcdFile, weight_ce0, "(port)weight_ce0");
    sc_trace(mVcdFile, weight_q0, "(port)weight_q0");
    sc_trace(mVcdFile, index_address0, "(port)index_address0");
    sc_trace(mVcdFile, index_ce0, "(port)index_ce0");
    sc_trace(mVcdFile, index_q0, "(port)index_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_88_p2, "i_fu_88_p2");
    sc_trace(mVcdFile, i_reg_108, "i_reg_108");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln5_fu_82_p2, "icmp_ln5_fu_82_p2");
    sc_trace(mVcdFile, hist_addr_reg_123, "hist_addr_reg_123");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, weight_load_reg_128, "weight_load_reg_128");
    sc_trace(mVcdFile, hist_load_reg_133, "hist_load_reg_133");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_fu_78_p2, "grp_fu_78_p2");
    sc_trace(mVcdFile, tmp_reg_138, "tmp_reg_138");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, i_0_reg_67, "i_0_reg_67");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, zext_ln6_fu_94_p1, "zext_ln6_fu_94_p1");
    sc_trace(mVcdFile, sext_ln6_fu_100_p1, "sext_ln6_fu_100_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("kernel3.hdltvin.dat");
    mHdltvoutHandle.open("kernel3.hdltvout.dat");
}

kernel3::~kernel3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete kernel3_fadd_32nsbkb_U1;
}

void kernel3::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void kernel3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_0_reg_67 = i_reg_108.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_67 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        hist_addr_reg_123 =  (sc_lv<10>) (sext_ln6_fu_100_p1.read());
        weight_load_reg_128 = weight_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        hist_load_reg_133 = hist_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_108 = i_fu_88_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tmp_reg_138 = grp_fu_78_p2.read();
    }
}

void kernel3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void kernel3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void kernel3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void kernel3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void kernel3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void kernel3::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void kernel3::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void kernel3::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln5_fu_82_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void kernel3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void kernel3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln5_fu_82_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void kernel3::thread_hist_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        hist_address0 = hist_addr_reg_123.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        hist_address0 =  (sc_lv<10>) (sext_ln6_fu_100_p1.read());
    } else {
        hist_address0 = "XXXXXXXXXX";
    }
}

void kernel3::thread_hist_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        hist_ce0 = ap_const_logic_1;
    } else {
        hist_ce0 = ap_const_logic_0;
    }
}

void kernel3::thread_hist_d0() {
    hist_d0 = tmp_reg_138.read();
}

void kernel3::thread_hist_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        hist_we0 = ap_const_logic_1;
    } else {
        hist_we0 = ap_const_logic_0;
    }
}

void kernel3::thread_i_fu_88_p2() {
    i_fu_88_p2 = (!i_0_reg_67.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_0_reg_67.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void kernel3::thread_icmp_ln5_fu_82_p2() {
    icmp_ln5_fu_82_p2 = (!i_0_reg_67.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_67.read() == ap_const_lv11_400);
}

void kernel3::thread_index_address0() {
    index_address0 =  (sc_lv<10>) (zext_ln6_fu_94_p1.read());
}

void kernel3::thread_index_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        index_ce0 = ap_const_logic_1;
    } else {
        index_ce0 = ap_const_logic_0;
    }
}

void kernel3::thread_sext_ln6_fu_100_p1() {
    sext_ln6_fu_100_p1 = esl_sext<64,32>(index_q0.read());
}

void kernel3::thread_weight_address0() {
    weight_address0 =  (sc_lv<10>) (zext_ln6_fu_94_p1.read());
}

void kernel3::thread_weight_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        weight_ce0 = ap_const_logic_1;
    } else {
        weight_ce0 = ap_const_logic_0;
    }
}

void kernel3::thread_zext_ln6_fu_94_p1() {
    zext_ln6_fu_94_p1 = esl_zext<64,11>(i_0_reg_67.read());
}

void kernel3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln5_fu_82_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

void kernel3::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hist_address0\" :  \"" << hist_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hist_ce0\" :  \"" << hist_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hist_we0\" :  \"" << hist_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"hist_d0\" :  \"" << hist_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"hist_q0\" :  \"" << hist_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_address0\" :  \"" << weight_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"weight_ce0\" :  \"" << weight_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"weight_q0\" :  \"" << weight_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"index_address0\" :  \"" << index_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"index_ce0\" :  \"" << index_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"index_q0\" :  \"" << index_q0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

