// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "kernel1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic kernel1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic kernel1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> kernel1::ap_ST_fsm_state1 = "1";
const sc_lv<3> kernel1::ap_ST_fsm_state2 = "10";
const sc_lv<3> kernel1::ap_ST_fsm_state3 = "100";
const sc_lv<32> kernel1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> kernel1::ap_const_lv32_1 = "1";
const sc_lv<1> kernel1::ap_const_lv1_0 = "0";
const sc_lv<11> kernel1::ap_const_lv11_0 = "00000000000";
const sc_lv<32> kernel1::ap_const_lv32_2 = "10";
const sc_lv<11> kernel1::ap_const_lv11_400 = "10000000000";
const sc_lv<11> kernel1::ap_const_lv11_1 = "1";
const sc_lv<1> kernel1::ap_const_lv1_1 = "1";
const bool kernel1::ap_const_boolean_1 = true;

kernel1::kernel1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln6_fu_50_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln6_fu_50_p2 );

    SC_METHOD(thread_array_r_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( array_addr_reg_88 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln7_fu_62_p1 );

    SC_METHOD(thread_array_r_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_array_r_d0);
    sensitive << ( array_r_q0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( shl_ln7_fu_67_p2 );

    SC_METHOD(thread_array_r_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_i_fu_56_p2);
    sensitive << ( i_0_reg_39 );

    SC_METHOD(thread_icmp_ln6_fu_50_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_39 );

    SC_METHOD(thread_shl_ln7_fu_67_p2);
    sensitive << ( array_r_q0 );

    SC_METHOD(thread_zext_ln7_fu_62_p1);
    sensitive << ( i_0_reg_39 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln6_fu_50_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "kernel1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, array_r_address0, "(port)array_r_address0");
    sc_trace(mVcdFile, array_r_ce0, "(port)array_r_ce0");
    sc_trace(mVcdFile, array_r_we0, "(port)array_r_we0");
    sc_trace(mVcdFile, array_r_d0, "(port)array_r_d0");
    sc_trace(mVcdFile, array_r_q0, "(port)array_r_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_56_p2, "i_fu_56_p2");
    sc_trace(mVcdFile, i_reg_83, "i_reg_83");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, array_addr_reg_88, "array_addr_reg_88");
    sc_trace(mVcdFile, icmp_ln6_fu_50_p2, "icmp_ln6_fu_50_p2");
    sc_trace(mVcdFile, i_0_reg_39, "i_0_reg_39");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln7_fu_62_p1, "zext_ln7_fu_62_p1");
    sc_trace(mVcdFile, shl_ln7_fu_67_p2, "shl_ln7_fu_67_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("kernel1.hdltvin.dat");
    mHdltvoutHandle.open("kernel1.hdltvout.dat");
}

kernel1::~kernel1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void kernel1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_0_reg_39 = i_reg_83.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_39 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln6_fu_50_p2.read(), ap_const_lv1_0))) {
        array_addr_reg_88 =  (sc_lv<10>) (zext_ln7_fu_62_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_83 = i_fu_56_p2.read();
    }
}

void kernel1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void kernel1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void kernel1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void kernel1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln6_fu_50_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void kernel1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void kernel1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln6_fu_50_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void kernel1::thread_array_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        array_r_address0 = array_addr_reg_88.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        array_r_address0 =  (sc_lv<10>) (zext_ln7_fu_62_p1.read());
    } else {
        array_r_address0 = "XXXXXXXXXX";
    }
}

void kernel1::thread_array_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        array_r_ce0 = ap_const_logic_1;
    } else {
        array_r_ce0 = ap_const_logic_0;
    }
}

void kernel1::thread_array_r_d0() {
    array_r_d0 = (!array_r_q0.read().is_01() || !shl_ln7_fu_67_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(array_r_q0.read()) + sc_biguint<32>(shl_ln7_fu_67_p2.read()));
}

void kernel1::thread_array_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        array_r_we0 = ap_const_logic_1;
    } else {
        array_r_we0 = ap_const_logic_0;
    }
}

void kernel1::thread_i_fu_56_p2() {
    i_fu_56_p2 = (!i_0_reg_39.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_0_reg_39.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void kernel1::thread_icmp_ln6_fu_50_p2() {
    icmp_ln6_fu_50_p2 = (!i_0_reg_39.read().is_01() || !ap_const_lv11_400.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_39.read() == ap_const_lv11_400);
}

void kernel1::thread_shl_ln7_fu_67_p2() {
    shl_ln7_fu_67_p2 = (!ap_const_lv32_2.is_01())? sc_lv<32>(): array_r_q0.read() << (unsigned short)ap_const_lv32_2.to_uint();
}

void kernel1::thread_zext_ln7_fu_62_p1() {
    zext_ln7_fu_62_p1 = esl_zext<64,11>(i_0_reg_39.read());
}

void kernel1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln6_fu_50_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

void kernel1::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_r_address0\" :  \"" << array_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_r_ce0\" :  \"" << array_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_r_we0\" :  \"" << array_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"array_r_d0\" :  \"" << array_r_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"array_r_q0\" :  \"" << array_r_q0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

