// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _kernel2_HH_
#define _kernel2_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct kernel2 : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > array_r_address0;
    sc_out< sc_logic > array_r_ce0;
    sc_in< sc_lv<32> > array_r_q0;
    sc_out< sc_lv<10> > array_r_address1;
    sc_out< sc_logic > array_r_ce1;
    sc_out< sc_logic > array_r_we1;
    sc_out< sc_lv<32> > array_r_d1;
    sc_in< sc_lv<32> > array_r_q1;


    // Module declarations
    kernel2(sc_module_name name);
    SC_HAS_PROCESS(kernel2);

    ~kernel2();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > reg_97;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln6_fu_101_p2;
    sc_signal< sc_lv<32> > array_load_2_reg_180;
    sc_signal< sc_lv<32> > mul_ln7_fu_140_p2;
    sc_signal< sc_lv<32> > mul_ln7_reg_185;
    sc_signal< sc_lv<11> > i_fu_156_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<11> > i_0_reg_85;
    sc_signal< sc_lv<64> > zext_ln7_1_fu_113_p1;
    sc_signal< sc_lv<64> > zext_ln7_2_fu_124_p1;
    sc_signal< sc_lv<64> > zext_ln7_fu_135_p1;
    sc_signal< sc_lv<64> > zext_ln7_3_fu_151_p1;
    sc_signal< sc_lv<11> > add_ln7_1_fu_107_p2;
    sc_signal< sc_lv<11> > add_ln7_2_fu_118_p2;
    sc_signal< sc_lv<11> > add_ln7_fu_129_p2;
    sc_signal< sc_lv<32> > add_ln7_3_fu_145_p0;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    sc_signal< bool > ap_enable_operation_36;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_enable_state5_pp0_iter0_stage3;
    sc_signal< bool > ap_enable_operation_17;
    sc_signal< bool > ap_enable_state2_pp0_iter0_stage0;
    sc_signal< bool > ap_enable_operation_26;
    sc_signal< bool > ap_enable_state3_pp0_iter0_stage1;
    sc_signal< bool > ap_enable_operation_21;
    sc_signal< bool > ap_enable_operation_27;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<11> ap_const_lv11_3;
    static const sc_lv<11> ap_const_lv11_400;
    static const sc_lv<11> ap_const_lv11_7FE;
    static const sc_lv<11> ap_const_lv11_7FD;
    static const sc_lv<11> ap_const_lv11_7FF;
    static const sc_lv<11> ap_const_lv11_1;
    static const sc_lv<32> ap_const_lv32_5;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln7_1_fu_107_p2();
    void thread_add_ln7_2_fu_118_p2();
    void thread_add_ln7_3_fu_145_p0();
    void thread_add_ln7_fu_129_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_enable_operation_17();
    void thread_ap_enable_operation_21();
    void thread_ap_enable_operation_26();
    void thread_ap_enable_operation_27();
    void thread_ap_enable_operation_36();
    void thread_ap_enable_pp0();
    void thread_ap_enable_state2_pp0_iter0_stage0();
    void thread_ap_enable_state3_pp0_iter0_stage1();
    void thread_ap_enable_state5_pp0_iter0_stage3();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_ready();
    void thread_array_r_address0();
    void thread_array_r_address1();
    void thread_array_r_ce0();
    void thread_array_r_ce1();
    void thread_array_r_d1();
    void thread_array_r_we1();
    void thread_i_fu_156_p2();
    void thread_icmp_ln6_fu_101_p2();
    void thread_mul_ln7_fu_140_p2();
    void thread_zext_ln7_1_fu_113_p1();
    void thread_zext_ln7_2_fu_124_p1();
    void thread_zext_ln7_3_fu_151_p1();
    void thread_zext_ln7_fu_135_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
